import { StrictMode, useState } from 'react'
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { DashboardReportSnapshot } from './dashboardReportTypes'
import { DashboardReportDialog } from './DashboardReportDialog'

const mocks = vi.hoisted(() => ({ loadSnapshot: vi.fn() }))
vi.mock('./dashboardReportData', () => ({ loadDashboardReportSnapshot: mocks.loadSnapshot }))

const baseSnapshot: DashboardReportSnapshot = {
  metadata: {
    title: 'CampusLink Administrative Usage Report',
    generatedAt: '2026-08-16T04:30:00.000Z',
    generatedBy: 'admin@nus.edu.sg',
    reportingPeriod: { days: 30, startDate: '2026-07-18', endDate: '2026-08-16' },
  },
  userManagement: {
    totalUsers: 4,
    roleDistribution: { STUDENT: 2, ADMIN: 1, SUPER_ADMIN: 1 },
    administratorCount: 1,
    superAdministratorCount: 1,
    unavailableMetrics: ['Recent registrations are unavailable because AdminUser has no createdAt field.'],
  },
  facilities: {
    bookingsInPeriod: 3,
    bookingStatusDistribution: { CONFIRMED: 1, COMPLETED: 1, CANCELLED: 1 },
    topFacilities: [{ facilityId: 5, facilityName: 'Seminar Room 2', reservationCount: 2 }],
    maintenanceRequestsInPeriod: 2,
    maintenanceStatusDistribution: { SUBMITTED: 1, IN_PROGRESS: 0, RESOLVED: 1, CANCELLED: 0 },
    unresolvedMaintenanceRequests: 2,
  },
  lostFound: {
    reportsInPeriod: 2,
    reportTypeDistribution: { LOST: 1, FOUND: 1 },
    reportStatusDistribution: { OPEN: 1, CLAIMED: 0, CLOSED: 1 },
    pendingClaims: 1,
    processedClaims: 2,
    claimMetricNote: 'Pending and processed claim counts come from the safe Lost & Found overview aggregate contract.',
  },
  administration: {
    actionsInPeriod: 2,
    scopeNote: 'Lost & Found administrative audit activity',
    actionDistribution: {
      REPORT_DELISTED: 0,
      REPORT_RESTORED: 0,
      REPORT_DELETED_BY_ADMIN: 0,
      CLAIM_APPROVED_BY_ADMIN: 1,
      CLAIM_REJECTED_BY_ADMIN: 0,
    },
    recentActivity: [
      {
        auditId: 10,
        reportId: 13,
        itemName: 'Blue Wallet',
        action: 'CLAIM_APPROVED_BY_ADMIN',
        actorEmail: 'admin@nus.edu.sg',
        createdAt: '2026-08-15T03:00:00Z',
      },
    ],
  },
}

function deferred<T>() {
  let resolve!: (value: T) => void
  let reject!: (reason?: unknown) => void
  const promise = new Promise<T>((onResolve, onReject) => {
    resolve = onResolve
    reject = onReject
  })
  return { promise, resolve, reject }
}

function Harness({ initiallyOpen = true }: { initiallyOpen?: boolean }) {
  const [open, setOpen] = useState(initiallyOpen)
  return (
    <>
      <button onClick={() => setOpen(true)}>Open report</button>
      <DashboardReportDialog open={open} generatedBy="admin@nus.edu.sg" onClose={() => setOpen(false)} />
    </>
  )
}

describe('DashboardReportDialog', () => {
  beforeEach(() => {
    mocks.loadSnapshot.mockReset()
    mocks.loadSnapshot.mockResolvedValue(baseSnapshot)
  })

  afterEach(() => cleanup())

  it('shows loading, then renders the Administrative Usage Report title, period, and aggregates', async () => {
    const pending = deferred<DashboardReportSnapshot>()
    mocks.loadSnapshot.mockReturnValue(pending.promise)
    render(<Harness />)

    expect(screen.getByRole('status')).toHaveTextContent('Generating administrative usage report')
    await act(async () => pending.resolve(baseSnapshot))

    const dialog = screen.getByRole('dialog', { name: 'Administrative Usage Report Preview' })
    expect(within(dialog).getByRole('heading', { name: 'CampusLink Administrative Usage Report' })).toBeInTheDocument()
    expect(dialog).toHaveTextContent('Administrative Usage Report')
    expect(dialog).toHaveTextContent('18 Jul 2026 – 16 Aug 2026')
    expect(dialog).toHaveTextContent('30 Singapore calendar days')
    expect(dialog).toHaveTextContent('Generated By: admin@nus.edu.sg')
    expect(dialog).toHaveTextContent('Total Users')
    expect(dialog).toHaveTextContent('Bookings in Period')
    expect(dialog).toHaveTextContent('Lost & Found Reports in Period')
    expect(dialog).toHaveTextContent('Administrative Actions in Period')
    expect(dialog).toHaveTextContent('Lost & Found administrative audit activity')
    expect(dialog).toHaveTextContent('Seminar Room 2')
    expect(dialog).toHaveTextContent('Blue Wallet')
  })

  it('resolves under React StrictMode without duplicate concurrent requests', async () => {
    const pending = deferred<DashboardReportSnapshot>()
    mocks.loadSnapshot.mockReturnValue(pending.promise)
    render(<StrictMode><Harness /></StrictMode>)

    expect(mocks.loadSnapshot).toHaveBeenCalledTimes(1)
    await act(async () => pending.resolve(baseSnapshot))
    expect(await screen.findByText('Bookings in Period')).toBeInTheDocument()
  })

  it('shows a complete error, hides partial content, and retries successfully', async () => {
    mocks.loadSnapshot.mockRejectedValueOnce(new Error('Audit unavailable')).mockResolvedValueOnce(baseSnapshot)
    render(<Harness />)

    expect(await screen.findByText('Failed to generate the complete administrative usage report.')).toBeInTheDocument()
    expect(screen.queryByText('Bookings in Period')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Retry' }))
    expect(await screen.findByText('Bookings in Period')).toBeInTheDocument()
    expect(mocks.loadSnapshot).toHaveBeenCalledTimes(2)
  })

  it('regenerates and replaces the previous immutable report snapshot', async () => {
    const regenerated = {
      ...baseSnapshot,
      administration: { ...baseSnapshot.administration, actionsInPeriod: 7 },
    } as DashboardReportSnapshot
    mocks.loadSnapshot.mockResolvedValueOnce(baseSnapshot).mockResolvedValueOnce(regenerated)
    render(<Harness />)

    expect(await screen.findByText('Administrative Actions in Period')).toBeInTheDocument()
    expect(screen.getByRole('group', { name: 'Administrative Actions in Period' })).toHaveTextContent('2')
    fireEvent.click(screen.getByRole('button', { name: 'Regenerate' }))
    await waitFor(() => expect(screen.getByRole('group', { name: 'Administrative Actions in Period' })).toHaveTextContent('7'))
  })

  it('closes, clears the in-memory snapshot, and ignores a late request', async () => {
    const pending = deferred<DashboardReportSnapshot>()
    mocks.loadSnapshot.mockReturnValueOnce(pending.promise).mockResolvedValueOnce(baseSnapshot)
    render(<Harness />)

    fireEvent.click(screen.getByRole('button', { name: 'Close' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    await act(async () => pending.resolve(baseSnapshot))
    expect(screen.queryByText('Bookings in Period')).not.toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: 'Open report' }))
    expect(await screen.findByText('Bookings in Period')).toBeInTheDocument()
    expect(mocks.loadSnapshot).toHaveBeenCalledTimes(2)
  })

  it('renders stable empty states', async () => {
    mocks.loadSnapshot.mockResolvedValue({
      ...baseSnapshot,
      facilities: {
        ...baseSnapshot.facilities,
        bookingsInPeriod: 0,
        topFacilities: [],
        maintenanceRequestsInPeriod: 0,
      },
      administration: { ...baseSnapshot.administration, actionsInPeriod: 0, recentActivity: [] },
    })
    render(<Harness />)

    expect(await screen.findByText('No active facility reservations were recorded in this reporting period.')).toBeInTheDocument()
    expect(screen.getByText('No administrative activity was recorded in this reporting period.')).toBeInTheDocument()
  })

  it('never renders unsafe claim, proof, image, or audit-detail fields from an unexpected payload', async () => {
    const unsafe = structuredClone(baseSnapshot) as unknown as Record<string, unknown>
    unsafe.proofSummary = 'DO NOT SHOW PROOF SUMMARY'
    unsafe.proofDescription = 'DO NOT SHOW PROOF DESCRIPTION'
    unsafe.decisionNote = 'DO NOT SHOW DECISION NOTE'
    unsafe.images = ['DO NOT SHOW REPORT IMAGE']
    unsafe.reason = 'DO NOT SHOW AUDIT REASON'
    unsafe.detail = 'DO NOT SHOW AUDIT DETAIL'
    mocks.loadSnapshot.mockResolvedValue(unsafe)
    render(<Harness />)

    await screen.findByText('Bookings in Period')
    expect(screen.queryByText(/DO NOT SHOW/)).not.toBeInTheDocument()
  })

  it('settles a pending request safely after unmount', async () => {
    const pending = deferred<DashboardReportSnapshot>()
    mocks.loadSnapshot.mockReturnValue(pending.promise)
    const { unmount } = render(<Harness />)
    unmount()
    await act(async () => pending.reject(new Error('late failure')))
  })
})





