@file:Suppress("LongMethod")

package com.campuslink.mobile.ui

import com.campuslink.mobile.core.settings.AppLanguage

data class UiStrings(
    val welcome: String,
    val subtitle: String,
    val email: String,
    val password: String,
    val confirmPassword: String,
    val login: String,
    val register: String,
    val switchToRegister: String,
    val switchToLogin: String,
    val conversations: String,
    val newChat: String,
    val noConversations: String,
    val typeMessage: String,
    val send: String,
    val stop: String,
    val settings: String,
    val logout: String,
    val clearHistory: String,
    val darkMode: String,
    val language: String,
    val confirmAction: String,
    val approve: String,
    val cancel: String,
    val agentSteps: String,
    val matches: String,
    val viewDetails: String,
    val delete: String,
    val retry: String,
    val dismiss: String,
    val switchLanguage: String,
    val showActivity: String,
    val hideActivity: String,
    val back: String,
    val shell: ShellStrings,
    val home: HomeStrings,
    val agentCore: AgentCoreStrings,
    val profile: ProfileStrings,
    val mail: MailStrings,
    val calendar: CalendarStrings,
)

data class MailStrings(
    val title: String,
    val detailsTitle: String,
    val connected: String,
    val connectedAccount: String,
    val disconnect: String,
    val disconnectQuestion: String,
    val disconnectMessage: String,
    val gmailDisconnected: String,
    val categoryCampus: String,
    val categoryCareer: String,
    val categoryFinance: String,
    val categoryOther: String,
    val connectTitle: String,
    val connectDescription: String,
    val authorizeGmail: String,
    val checkAgain: String,
    val calendar: String,
    val compose: String,
    val refresh: String,
    val inbox: String,
    val sent: String,
    val archive: String,
    val trash: String,
    val spam: String,
    val searchMail: String,
    val search: String,
    val unread: String,
    val starred: String,
    val markRead: String,
    val markUnread: String,
    val star: String,
    val unstar: String,
    val loadMore: String,
    val noMessages: String,
    val noSubject: String,
    val noBody: String,
    val from: String,
    val date: String,
    val to: String,
    val newMessage: String,
    val recipients: String,
    val recipientsHelper: String,
    val subject: String,
    val message: String,
    val send: String,
    val cancel: String,
    val back: String,
    val loading: String,
    val loadingMessage: String,
    val unableToLoad: String,
    val unableToLoadMessage: String,
    val retry: String,
    val waitingAuthorization: String,
    val gmailConnectedMessage: String,
    val authorizationPending: String,
    val messageUpdated: String,
)

data class CalendarStrings(
    val title: String,
    val events: String,
    val monthView: String,
    val today: String,
    val previousMonth: String,
    val nextMonth: String,
    val weekdayLabels: List<String>,
    val addEvent: String,
    val extractFromMail: String,
    val scan: String,
    val scanWindow: String,
    val mode: String,
    val aiMode: String,
    val rulesMode: String,
    val scanToday: String,
    val scanTwoDays: String,
    val scanThreeDays: String,
    val scanFourDays: String,
    val scanEightDays: String,
    val viewSourceEmail: String,
    val scanning: String,
    val suggestedEvents: String,
    val importSelected: String,
    val myEvents: String,
    val noEvents: String,
    val newEvent: String,
    val editEvent: String,
    val eventTitle: String,
    val description: String,
    val location: String,
    val startTime: String,
    val endTime: String,
    val allDay: String,
    val cancel: String,
    val save: String,
    val deleteEvent: String,
    val deleteQuestion: String,
    val deleteMessage: String,
    val fromMail: String,
    val edit: String,
    val delete: String,
    val back: String,
    val loading: String,
    val unableToLoad: String,
    val retry: String,
    val eventCreated: String,
    val eventUpdated: String,
    val eventDeleted: String,
    val scannedEmails: String,
    val importedEvents: String,
)

data class ShellStrings(
    val home: String,
    val agentCore: String,
    val profile: String,
)

data class HomeStrings(
    val goodMorning: String,
    val goodAfternoon: String,
    val goodEvening: String,
    val appName: String,
    val subtitle: String,
    val agentName: String,
    val agentTagline: String,
    val agentDescription: String,
    val askAgent: String,
    val campusServices: String,
    val facilities: String,
    val facilitiesSubtitle: String,
    val lostFound: String,
    val lostFoundSubtitle: String,
    val mail: String,
    val mailSubtitle: String,
    val quickAccess: String,
    val myBookings: String,
    val bookingsSubtitle: String,
    val myMaintenance: String,
    val maintenanceSubtitle: String,
    val myClaims: String,
    val claimsSubtitle: String,
)

data class AgentCoreStrings(
    val title: String,
    val subtitle: String,
    val newChat: String,
    val recentConversations: String,
    val emptyTitle: String,
    val emptySubtitle: String,
    val startNewChat: String,
    val deleteConversation: String,
)

data class ProfileStrings(
    val title: String,
    val subtitle: String,
    val preferences: String,
    val darkMode: String,
    val language: String,
    val english: String,
    val chinese: String,
    val dataPrivacy: String,
    val clearHistory: String,
    val clearHistoryTitle: String,
    val clearHistoryMessage: String,
    val clear: String,
    val about: String,
    val aboutCampusLink: String,
    val aboutSubtitle: String,
    val version: String,
    val logOut: String,
    val confirmLogOut: String,
    val logOutTitle: String,
    val logOutMessage: String,
    val role: String,
    val cancel: String,
)

fun strings(language: AppLanguage): UiStrings = if (language == AppLanguage.CHINESE) {
    chineseStrings()
} else {
    englishStrings()
}

private fun chineseStrings(): UiStrings = UiStrings(
        "欢迎使用 CampusLink", "登录后使用校园 AI 助手和服务", "邮箱", "密码", "确认密码",
        "登录", "注册", "没有账号？注册", "已有账号？登录", "对话", "新对话", "还没有对话",
        "输入消息…", "发送", "停止", "设置", "退出登录", "清除本地记录", "深色模式", "语言",
        "需要确认操作", "确认", "取消", "Agent 执行过程", "匹配结果", "查看详情", "删除", "重试", "关闭",
        "English", "展开执行过程", "收起执行过程", "返回",
        ShellStrings("首页", "Agent Core", "个人资料"),
        HomeStrings(
            goodMorning = "早上好",
            goodAfternoon = "下午好",
            goodEvening = "晚上好",
            appName = "CampusLink",
            subtitle = "连接你的校园生活。",
            agentName = "CampusAgent",
            agentTagline = "你的 AI 校园助手",
            agentDescription = "咨询校园服务、场地预订、失物招领和邮件。",
            askAgent = "咨询 Agent",
            campusServices = "校园服务",
            facilities = "设施",
            facilitiesSubtitle = "预订空间并报告问题",
            lostFound = "失物招领",
            lostFoundSubtitle = "查找或报告物品",
            mail = "邮件",
            mailSubtitle = "查看邮件与管理日历",
            quickAccess = "快捷入口",
            myBookings = "我的预订",
            bookingsSubtitle = "查看即将到来的预订",
            myMaintenance = "我的维修",
            maintenanceSubtitle = "跟踪已提交的请求",
            myClaims = "我的认领",
            claimsSubtitle = "查看失物招领认领记录",
        ),
        AgentCoreStrings(
            title = "Agent Core",
            subtitle = "CampusLink AI 助手",
            newChat = "新建对话",
            recentConversations = "最近对话",
            emptyTitle = "开始一段对话",
            emptySubtitle = "向 CampusAgent 咨询设施、失物招领、邮件和校园服务。",
            startNewChat = "开始新对话",
            deleteConversation = "删除对话",
        ),
        ProfileStrings(
            title = "个人资料",
            subtitle = "账户与应用偏好",
            preferences = "偏好设置",
            darkMode = "深色模式",
            language = "语言",
            english = "English",
            chinese = "中文",
            dataPrivacy = "数据与隐私",
            clearHistory = "清除聊天记录",
            clearHistoryTitle = "清除聊天记录？",
            clearHistoryMessage = "这将永久删除你的本地对话记录。",
            clear = "清除",
            about = "关于",
            aboutCampusLink = "关于 CampusLink",
            aboutSubtitle = "校园服务与 AI 助手，尽在一个应用",
            version = "版本",
            logOut = "退出登录",
            confirmLogOut = "退出登录",
            logOutTitle = "退出登录？",
            logOutMessage = "你确定要退出 CampusLink 吗？",
            role = "角色",
            cancel = "取消",
        ),
        MailStrings(
            title = "邮件",
            detailsTitle = "邮件详情",
            connected = "已连接",
            connectedAccount = "已连接 · %s",
            disconnect = "断开 Gmail",
            disconnectQuestion = "断开 Gmail？",
            disconnectMessage = "断开后需要重新授权才能继续使用邮件和日历。",
            gmailDisconnected = "Gmail 已断开",
            categoryCampus = "校园",
            categoryCareer = "职业",
            categoryFinance = "财务",
            categoryOther = "其他",
            connectTitle = "连接 Gmail",
            connectDescription = "授权 CampusLink 后即可在应用内查看和管理邮件。",
            authorizeGmail = "授权 Gmail",
            checkAgain = "重新检查",
            calendar = "日历",
            compose = "写邮件",
            refresh = "刷新",
            inbox = "收件箱",
            sent = "已发送",
            archive = "归档",
            trash = "垃圾箱",
            spam = "垃圾邮件",
            searchMail = "搜索邮件",
            search = "搜索",
            unread = "未读",
            starred = "已加星标",
            markRead = "标为已读",
            markUnread = "标为未读",
            star = "加星标",
            unstar = "取消星标",
            loadMore = "加载更多",
            noMessages = "%s中没有邮件。",
            noSubject = "（无主题）",
            noBody = "没有正文",
            from = "发件人",
            date = "时间",
            to = "收件人：%s",
            newMessage = "新邮件",
            recipients = "收件人",
            recipientsHelper = "多个邮箱请用英文逗号分隔",
            subject = "主题",
            message = "正文",
            send = "发送",
            cancel = "取消",
            back = "返回",
            loading = "正在加载邮件…",
            loadingMessage = "正在加载邮件详情…",
            unableToLoad = "无法加载邮件",
            unableToLoadMessage = "无法加载邮件详情",
            retry = "重试",
            waitingAuthorization = "正在等待 Gmail 授权…",
            gmailConnectedMessage = "Gmail 已连接",
            authorizationPending = "尚未检测到授权，请点击“重新检查”。",
            messageUpdated = "邮件已更新",
        ),
        CalendarStrings(
            title = "日历",
            events = "日程",
            monthView = "月视图",
            today = "今天",
            previousMonth = "上个月",
            nextMonth = "下个月",
            weekdayLabels = listOf("日", "一", "二", "三", "四", "五", "六"),
            addEvent = "添加日程",
            extractFromMail = "从邮件提取日程",
            scan = "扫描",
            scanWindow = "选择要扫描的邮件时间范围",
            mode = "识别模式",
            aiMode = "AI",
            rulesMode = "规则",
            scanToday = "仅今天",
            scanTwoDays = "今天+昨天",
            scanThreeDays = "近 3 天",
            scanFourDays = "近 4 天",
            scanEightDays = "近 8 天",
            viewSourceEmail = "查看来源邮件",
            scanning = "正在扫描…",
            suggestedEvents = "建议的日程",
            importSelected = "导入所选日程",
            myEvents = "我的日程",
            noEvents = "暂无日程。",
            newEvent = "新建日程",
            editEvent = "编辑日程",
            eventTitle = "标题",
            description = "描述",
            location = "地点",
            startTime = "开始时间（ISO-8601）",
            endTime = "结束时间（ISO-8601）",
            allDay = "全天",
            cancel = "取消",
            save = "保存",
            deleteEvent = "删除日程",
            deleteQuestion = "删除此日程？",
            deleteMessage = "“%s”将被永久删除。",
            fromMail = "来自邮件",
            edit = "编辑",
            delete = "删除",
            back = "返回",
            loading = "正在加载日程…",
            unableToLoad = "无法加载日历",
            retry = "重试",
            eventCreated = "日程已创建",
            eventUpdated = "日程已更新",
            eventDeleted = "日程已删除",
            scannedEmails = "已扫描 %s 封邮件（%s 模式）",
            importedEvents = "已导入 %s 个日程；跳过 %s 个",
        ),
)

private fun englishStrings(): UiStrings = UiStrings(
        "Welcome to CampusLink", "Sign in to use the campus AI assistant and services", "Email", "Password",
        "Confirm password", "Login", "Register", "New here? Register", "Already registered? Login",
        "Conversations", "New chat", "No conversations yet", "Type a message…", "Send", "Stop", "Settings",
        "Logout", "Clear local history", "Dark mode", "Language", "Action confirmation required", "Confirm",
        "Cancel", "Agent activity", "Match results", "View details", "Delete", "Retry", "Dismiss",
        "中文", "Show activity", "Hide activity", "Back",
        ShellStrings("Home", "Agent Core", "Profile"),
        HomeStrings(
            goodMorning = "Good morning",
            goodAfternoon = "Good afternoon",
            goodEvening = "Good evening",
            appName = "CampusLink",
            subtitle = "Your campus, connected.",
            agentName = "CampusAgent",
            agentTagline = "Your AI-powered campus assistant",
            agentDescription = "Ask about campus services, bookings, lost items and email.",
            askAgent = "Ask Agent",
            campusServices = "Campus Services",
            facilities = "Facilities",
            facilitiesSubtitle = "Book rooms & report issues",
            lostFound = "Lost & Found",
            lostFoundSubtitle = "Find or report items",
            mail = "Mail",
            mailSubtitle = "Read mail & manage calendar",
            quickAccess = "Quick Access",
            myBookings = "My Bookings",
            bookingsSubtitle = "View upcoming reservations",
            myMaintenance = "My Maintenance",
            maintenanceSubtitle = "Track submitted requests",
            myClaims = "My Claims",
            claimsSubtitle = "Review Lost & Found claims",
        ),
        AgentCoreStrings(
            title = "Agent Core",
            subtitle = "CampusLink AI assistant",
            newChat = "New Chat",
            recentConversations = "Recent Conversations",
            emptyTitle = "Start a conversation",
            emptySubtitle = "Ask CampusAgent about facilities, lost items, email and campus services.",
            startNewChat = "Start New Chat",
            deleteConversation = "Delete conversation",
        ),
        ProfileStrings(
            title = "Profile",
            subtitle = "Account and app preferences",
            preferences = "Preferences",
            darkMode = "Dark Mode",
            language = "Language",
            english = "English",
            chinese = "中文",
            dataPrivacy = "Data & Privacy",
            clearHistory = "Clear Chat History",
            clearHistoryTitle = "Clear chat history?",
            clearHistoryMessage = "This will permanently delete your local conversation history.",
            clear = "Clear",
            about = "About",
            aboutCampusLink = "About CampusLink",
            aboutSubtitle = "Campus services and AI assistance in one app",
            version = "Version",
            logOut = "Log Out",
            confirmLogOut = "Log out",
            logOutTitle = "Log out?",
            logOutMessage = "Are you sure you want to log out of CampusLink?",
            role = "Role",
            cancel = "Cancel",
        ),
        MailStrings(
            title = "Mail",
            detailsTitle = "Message details",
            connected = "Connected",
            connectedAccount = "Connected · %s",
            disconnect = "Disconnect Gmail",
            disconnectQuestion = "Disconnect Gmail?",
            disconnectMessage = "You will need to authorize Gmail again before using mail and calendar.",
            gmailDisconnected = "Gmail disconnected",
            categoryCampus = "Campus",
            categoryCareer = "Career",
            categoryFinance = "Finance",
            categoryOther = "Other",
            connectTitle = "Connect Gmail",
            connectDescription = "Authorize CampusLink to read and manage your mail in one place.",
            authorizeGmail = "Authorize Gmail",
            checkAgain = "Check again",
            calendar = "Calendar",
            compose = "Compose",
            refresh = "Refresh",
            inbox = "Inbox",
            sent = "Sent",
            archive = "Archive",
            trash = "Trash",
            spam = "Spam",
            searchMail = "Search mail",
            search = "Search",
            unread = "Unread",
            starred = "Starred",
            markRead = "Mark read",
            markUnread = "Mark unread",
            star = "Star",
            unstar = "Unstar",
            loadMore = "Load more",
            noMessages = "No messages in %s.",
            noSubject = "(No subject)",
            noBody = "No message body",
            from = "From",
            date = "Date",
            to = "To: %s",
            newMessage = "New message",
            recipients = "Recipients",
            recipientsHelper = "Separate multiple addresses with commas",
            subject = "Subject",
            message = "Message",
            send = "Send",
            cancel = "Cancel",
            back = "Back",
            loading = "Loading mail…",
            loadingMessage = "Loading message…",
            unableToLoad = "Unable to load mail",
            unableToLoadMessage = "Unable to load message",
            retry = "Retry",
            waitingAuthorization = "Waiting for Gmail authorization…",
            gmailConnectedMessage = "Gmail connected",
            authorizationPending = "Authorization not detected yet. Tap Check again.",
            messageUpdated = "Message updated",
        ),
        CalendarStrings(
            title = "Calendar",
            events = "Events",
            monthView = "Month view",
            today = "Today",
            previousMonth = "Previous month",
            nextMonth = "Next month",
            weekdayLabels = listOf("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"),
            addEvent = "Add event",
            extractFromMail = "Extract events from mail",
            scan = "Scan",
            scanWindow = "Choose how far back to scan your mail",
            mode = "Mode",
            aiMode = "AI",
            rulesMode = "Rules",
            scanToday = "Today only",
            scanTwoDays = "Today + yesterday",
            scanThreeDays = "Last 3 days",
            scanFourDays = "Last 4 days",
            scanEightDays = "Last 8 days",
            viewSourceEmail = "View source email",
            scanning = "Scanning…",
            suggestedEvents = "Suggested events",
            importSelected = "Import selected",
            myEvents = "My events",
            noEvents = "No events yet.",
            newEvent = "New event",
            editEvent = "Edit event",
            eventTitle = "Title",
            description = "Description",
            location = "Location",
            startTime = "Start time (ISO-8601)",
            endTime = "End time (ISO-8601)",
            allDay = "All day",
            cancel = "Cancel",
            save = "Save",
            deleteEvent = "Delete event",
            deleteQuestion = "Delete this event?",
            deleteMessage = "“%s” will be permanently removed.",
            fromMail = "From mail",
            edit = "Edit",
            delete = "Delete",
            back = "Back",
            loading = "Loading events…",
            unableToLoad = "Unable to load calendar",
            retry = "Retry",
            eventCreated = "Event created",
            eventUpdated = "Event updated",
            eventDeleted = "Event deleted",
            scannedEmails = "Scanned %s emails (%s mode)",
            importedEvents = "Imported %s events; skipped %s",
        ),
)
