package com.campuslink.mobile.ui

import com.campuslink.mobile.core.settings.AppLanguage

data class UiStrings(
    val welcome: String,
    val subtitle: String,
    val email: String,
    val password: String,
    val confirmPassword: String,
    val login: String,
    val register: String,
    val switchToRegister: String,
    val switchToLogin: String,
    val conversations: String,
    val newChat: String,
    val noConversations: String,
    val typeMessage: String,
    val send: String,
    val stop: String,
    val settings: String,
    val logout: String,
    val clearHistory: String,
    val darkMode: String,
    val language: String,
    val confirmAction: String,
    val approve: String,
    val cancel: String,
    val agentSteps: String,
    val matches: String,
    val delete: String,
    val retry: String,
    val dismiss: String,
    val switchLanguage: String,
    val showActivity: String,
    val hideActivity: String,
    val back: String,
    val shell: ShellStrings,
    val home: HomeStrings,
    val agentCore: AgentCoreStrings,
    val profile: ProfileStrings,
)

data class ShellStrings(
    val home: String,
    val agentCore: String,
    val profile: String,
)

data class HomeStrings(
    val goodMorning: String,
    val goodAfternoon: String,
    val goodEvening: String,
    val appName: String,
    val subtitle: String,
    val agentName: String,
    val agentTagline: String,
    val agentDescription: String,
    val askAgent: String,
    val campusServices: String,
    val facilities: String,
    val facilitiesSubtitle: String,
    val lostFound: String,
    val lostFoundSubtitle: String,
    val mail: String,
    val mailSubtitle: String,
    val agentBadge: String,
    val quickAccess: String,
    val myBookings: String,
    val bookingsSubtitle: String,
    val myMaintenance: String,
    val maintenanceSubtitle: String,
    val myClaims: String,
    val claimsSubtitle: String,
)

data class AgentCoreStrings(
    val title: String,
    val subtitle: String,
    val newChat: String,
    val recentConversations: String,
    val emptyTitle: String,
    val emptySubtitle: String,
    val startNewChat: String,
    val deleteConversation: String,
)

data class ProfileStrings(
    val title: String,
    val subtitle: String,
    val preferences: String,
    val darkMode: String,
    val language: String,
    val english: String,
    val chinese: String,
    val dataPrivacy: String,
    val clearHistory: String,
    val clearHistoryTitle: String,
    val clearHistoryMessage: String,
    val clear: String,
    val about: String,
    val aboutCampusLink: String,
    val aboutSubtitle: String,
    val version: String,
    val logOut: String,
    val confirmLogOut: String,
    val logOutTitle: String,
    val logOutMessage: String,
    val role: String,
    val cancel: String,
)

fun strings(language: AppLanguage): UiStrings = if (language == AppLanguage.CHINESE) {
    chineseStrings()
} else {
    englishStrings()
}

private fun chineseStrings(): UiStrings = UiStrings(
        "欢迎使用 CampusLink", "登录后使用校园 AI 助手和服务", "邮箱", "密码", "确认密码",
        "登录", "注册", "没有账号？注册", "已有账号？登录", "对话", "新对话", "还没有对话",
        "输入消息…", "发送", "停止", "设置", "退出登录", "清除本地记录", "深色模式", "语言",
        "需要确认操作", "确认", "取消", "Agent 执行过程", "匹配结果", "删除", "重试", "关闭",
        "English", "展开执行过程", "收起执行过程", "返回",
        ShellStrings("首页", "Agent Core", "个人资料"),
        HomeStrings(
            goodMorning = "早上好",
            goodAfternoon = "下午好",
            goodEvening = "晚上好",
            appName = "CampusLink",
            subtitle = "连接你的校园生活。",
            agentName = "CampusAgent",
            agentTagline = "你的 AI 校园助手",
            agentDescription = "咨询校园服务、场地预订、失物招领和邮件。",
            askAgent = "咨询 Agent",
            campusServices = "校园服务",
            facilities = "设施",
            facilitiesSubtitle = "预订空间并报告问题",
            lostFound = "失物招领",
            lostFoundSubtitle = "查找或报告物品",
            mail = "邮件",
            mailSubtitle = "由 Agent 管理",
            agentBadge = "Agent",
            quickAccess = "快捷入口",
            myBookings = "我的预订",
            bookingsSubtitle = "查看即将到来的预订",
            myMaintenance = "我的维修",
            maintenanceSubtitle = "跟踪已提交的请求",
            myClaims = "我的认领",
            claimsSubtitle = "查看失物招领认领记录",
        ),
        AgentCoreStrings(
            title = "Agent Core",
            subtitle = "CampusLink AI 助手",
            newChat = "新建对话",
            recentConversations = "最近对话",
            emptyTitle = "开始一段对话",
            emptySubtitle = "向 CampusAgent 咨询设施、失物招领、邮件和校园服务。",
            startNewChat = "开始新对话",
            deleteConversation = "删除对话",
        ),
        ProfileStrings(
            title = "个人资料",
            subtitle = "账户与应用偏好",
            preferences = "偏好设置",
            darkMode = "深色模式",
            language = "语言",
            english = "English",
            chinese = "中文",
            dataPrivacy = "数据与隐私",
            clearHistory = "清除聊天记录",
            clearHistoryTitle = "清除聊天记录？",
            clearHistoryMessage = "这将永久删除你的本地对话记录。",
            clear = "清除",
            about = "关于",
            aboutCampusLink = "关于 CampusLink",
            aboutSubtitle = "校园服务与 AI 助手，尽在一个应用",
            version = "版本",
            logOut = "退出登录",
            confirmLogOut = "退出登录",
            logOutTitle = "退出登录？",
            logOutMessage = "你确定要退出 CampusLink 吗？",
            role = "角色",
            cancel = "取消",
        ),
)

private fun englishStrings(): UiStrings = UiStrings(
        "Welcome to CampusLink", "Sign in to use the campus AI assistant and services", "Email", "Password",
        "Confirm password", "Login", "Register", "New here? Register", "Already registered? Login",
        "Conversations", "New chat", "No conversations yet", "Type a message…", "Send", "Stop", "Settings",
        "Logout", "Clear local history", "Dark mode", "Language", "Action confirmation required", "Confirm",
        "Cancel", "Agent activity", "Match results", "Delete", "Retry", "Dismiss",
        "中文", "Show activity", "Hide activity", "Back",
        ShellStrings("Home", "Agent Core", "Profile"),
        HomeStrings(
            goodMorning = "Good morning",
            goodAfternoon = "Good afternoon",
            goodEvening = "Good evening",
            appName = "CampusLink",
            subtitle = "Your campus, connected.",
            agentName = "CampusAgent",
            agentTagline = "Your AI-powered campus assistant",
            agentDescription = "Ask about campus services, bookings, lost items and email.",
            askAgent = "Ask Agent",
            campusServices = "Campus Services",
            facilities = "Facilities",
            facilitiesSubtitle = "Book rooms & report issues",
            lostFound = "Lost & Found",
            lostFoundSubtitle = "Find or report items",
            mail = "Mail",
            mailSubtitle = "Managed by Agent",
            agentBadge = "Agent",
            quickAccess = "Quick Access",
            myBookings = "My Bookings",
            bookingsSubtitle = "View upcoming reservations",
            myMaintenance = "My Maintenance",
            maintenanceSubtitle = "Track submitted requests",
            myClaims = "My Claims",
            claimsSubtitle = "Review Lost & Found claims",
        ),
        AgentCoreStrings(
            title = "Agent Core",
            subtitle = "CampusLink AI assistant",
            newChat = "New Chat",
            recentConversations = "Recent Conversations",
            emptyTitle = "Start a conversation",
            emptySubtitle = "Ask CampusAgent about facilities, lost items, email and campus services.",
            startNewChat = "Start New Chat",
            deleteConversation = "Delete conversation",
        ),
        ProfileStrings(
            title = "Profile",
            subtitle = "Account and app preferences",
            preferences = "Preferences",
            darkMode = "Dark Mode",
            language = "Language",
            english = "English",
            chinese = "中文",
            dataPrivacy = "Data & Privacy",
            clearHistory = "Clear Chat History",
            clearHistoryTitle = "Clear chat history?",
            clearHistoryMessage = "This will permanently delete your local conversation history.",
            clear = "Clear",
            about = "About",
            aboutCampusLink = "About CampusLink",
            aboutSubtitle = "Campus services and AI assistance in one app",
            version = "Version",
            logOut = "Log Out",
            confirmLogOut = "Log out",
            logOutTitle = "Log out?",
            logOutMessage = "Are you sure you want to log out of CampusLink?",
            role = "Role",
            cancel = "Cancel",
        ),
)
