package com.app.campusagent.facilities.exception;

public enum FacilityErrorCode {
    SPACE_NOT_FOUND,
    INVALID_SPACE_TYPE,
    INVALID_CAPACITY,
    INVALID_TIME,
    SPACE_UNAVAILABLE,
    BOOKING_CONFLICT,
    BOOKING_NOT_FOUND,
    BOOKING_CANCELLATION_NOT_ALLOWED,
    TICKET_NOT_FOUND,
    INVALID_LOCATION,
    INVALID_MAINTENANCE_REQUEST,
    INVALID_MAINTENANCE_STATUS,
    INVALID_MAINTENANCE_TRANSITION,
    INVALID_PRIORITY,
    AUTHENTICATION_REQUIRED
}
