import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Divider, MenuItem, Select, Stack, Tab, Tabs, TextField, Typography } from '@mui/material'
import { Link as RouterLink, useLocation, useNavigate, useParams } from 'react-router-dom'
import { useEffect, useMemo, useState } from 'react'
import { apiErrorMessage } from '../../api/client'
import { AdminBooking, facilitiesApi, FacilitiesDashboard, MaintenanceRequest } from '../../api/facilities'

const statusLabel = (value: string) => value.replaceAll('_', ' ')
const statusColor = (status: string) => ['AVAILABLE', 'CONFIRMED', 'COMPLETED', 'RESOLVED'].includes(status) ? 'success' : ['OUT_OF_SERVICE', 'IN_PROGRESS'].includes(status) ? 'warning' : 'default'
const tableSx = { width: '100%', borderCollapse: 'collapse', '& th, & td': { textAlign: 'left', p: 1.5, borderBottom: '1px solid', borderColor: 'divider', whiteSpace: 'nowrap' } }

function FacilitiesNav() {
  const path = useLocation().pathname
  const value = path.includes('reservations') ? 'reservations' : path.includes('maintenance') ? 'maintenance' : 'dashboard'
  return <Tabs value={value} sx={{ mb: 3 }} aria-label="Facilities sections"><Tab label="Dashboard" value="dashboard" component={RouterLink} to="/admin/facilities" /><Tab label="Reservations" value="reservations" component={RouterLink} to="/admin/facilities/reservations" /><Tab label="Maintenance" value="maintenance" component={RouterLink} to="/admin/facilities/maintenance" /></Tabs>
}
function Loading() { return <Box sx={{ display: 'grid', placeItems: 'center', minHeight: '15rem' }}><CircularProgress /></Box> }
function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <Alert severity="error" action={<Button color="inherit" size="small" onClick={retry}>Retry</Button>}>{message}</Alert> }
function Metric({ label, value, detail }: { label: string; value: number; detail: string }) { return <Card variant="outlined"><CardContent><Typography color="text.secondary" variant="body2">{label}</Typography><Typography variant="h4" fontWeight={700} sx={{ my: 1 }}>{value}</Typography><Typography variant="body2" color="text.secondary">{detail}</Typography></CardContent></Card> }
function SortButton({ label, active, ascending, onClick }: { label: string; active: boolean; ascending: boolean; onClick: () => void }) { return <Button size="small" onClick={onClick}>{label}{active ? (ascending ? ' ↑' : ' ↓') : ''}</Button> }
function nextStatuses(status: string) { if (status === 'SUBMITTED') return ['SUBMITTED', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED']; if (status === 'IN_PROGRESS') return ['IN_PROGRESS', 'RESOLVED', 'CANCELLED']; return [status] }
function reservationLabel(start: string, end: string) { return `${new Date(start).toLocaleDateString()} ${new Date(start).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}–${new Date(end).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` }
function recentReservationCount(reservations: { startDateTime: string; status: string }[]) { const from = new Date(); from.setDate(from.getDate() - 30); const to = new Date(); to.setDate(to.getDate() + 30); return reservations.filter((reservation) => reservation.status !== 'CANCELLED' && new Date(reservation.startDateTime) >= from && new Date(reservation.startDateTime) <= to).length }

export function FacilitiesDashboardPage() {
  const [data, setData] = useState<FacilitiesDashboard | null>(null); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [status, setStatus] = useState('All'); const [sort, setSort] = useState('name'); const [ascending, setAscending] = useState(true)
  const load = () => { setError(''); facilitiesApi.getDashboard().then(setData).catch((e) => setError(apiErrorMessage(e))) }; useEffect(load, [])
  const facilities = useMemo(() => [...(data?.facilities ?? [])].filter((item) => (status === 'All' || item.status === status) && `${item.name} ${item.building} ${item.roomNumber} ${item.spaceType}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => { const left = sort === 'capacity' ? a.capacity : sort === 'status' ? a.status : sort === 'building' ? a.building : sort === 'room' ? a.roomNumber : sort === 'type' ? a.spaceType : a.name; const right = sort === 'capacity' ? b.capacity : sort === 'status' ? b.status : sort === 'building' ? b.building : sort === 'room' ? b.roomNumber : sort === 'type' ? b.spaceType : b.name; const result = typeof left === 'number' && typeof right === 'number' ? left - right : String(left).localeCompare(String(right)); return ascending ? result : -result }), [data, query, sort, status, ascending])
  const toggleSort = (column: string) => { if (sort === column) setAscending((value) => !value); else { setSort(column); setAscending(true) } }
  return <Box sx={{ display: 'grid', gap: 3 }}><Typography component="h1" variant="h4" fontWeight={700}>Facilities Dashboard</Typography><FacilitiesNav />{error ? <ErrorState message={error} retry={load} /> : !data ? <Loading /> : <><Box sx={{ display: 'grid', gap: 2, gridTemplateColumns: { xs: '1fr 1fr', lg: 'repeat(4, 1fr)' } }}><Metric label="Total Facilities" value={data.summary.totalFacilities} detail="Registered facilities" /><Metric label="Available Facilities" value={data.summary.availableFacilities} detail="Ready for booking" /><Metric label="Today's Reservations" value={data.summary.todayReservations} detail="Across all facilities" /><Metric label="Under Maintenance" value={data.summary.underMaintenance} detail="Currently unavailable" /></Box><Card variant="outlined"><CardContent><Typography component="h2" variant="h6" fontWeight={700} sx={{ mb: 2 }}>All Facilities</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} sx={{ mb: 2 }}><TextField label="Search facilities" value={query} onChange={(e) => setQuery(e.target.value)} size="small" fullWidth /><Select value={status} onChange={(e) => setStatus(e.target.value)} size="small" aria-label="Filter by facility status"><MenuItem value="All">All statuses</MenuItem><MenuItem value="AVAILABLE">Available</MenuItem><MenuItem value="OUT_OF_SERVICE">Out of service</MenuItem><MenuItem value="INACTIVE">Inactive</MenuItem></Select></Stack><Box sx={{ overflowX: 'auto' }}><Box component="table" sx={tableSx}><thead><tr><th><SortButton label="Facility" active={sort === 'name'} ascending={ascending} onClick={() => toggleSort('name')} /></th><th><SortButton label="Building" active={sort === 'building'} ascending={ascending} onClick={() => toggleSort('building')} /></th><th><SortButton label="Room" active={sort === 'room'} ascending={ascending} onClick={() => toggleSort('room')} /></th><th><SortButton label="Type" active={sort === 'type'} ascending={ascending} onClick={() => toggleSort('type')} /></th><th><SortButton label="Capacity" active={sort === 'capacity'} ascending={ascending} onClick={() => toggleSort('capacity')} /></th><th><SortButton label="Status" active={sort === 'status'} ascending={ascending} onClick={() => toggleSort('status')} /></th><th>Recent Reservations</th><th>Details</th></tr></thead><tbody>{facilities.map((facility) => <tr key={facility.spaceId}><td>{facility.name}</td><td>{facility.building}</td><td>{facility.roomNumber}</td><td>{statusLabel(facility.spaceType)}</td><td>{facility.capacity}</td><td><Chip label={statusLabel(facility.status)} size="small" color={statusColor(facility.status)} /></td><td>{recentReservationCount(facility.reservations)}</td><td><Button component={RouterLink} to={`/admin/facilities/spaces/${facility.spaceId}/reservations`} size="small">Reservation Details</Button></td></tr>)}</tbody></Box></Box></CardContent></Card></>}</Box>
}

export function ReservationsPage() {
  const [rows, setRows] = useState<AdminBooking[]>([]); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All'); const [sort, setSort] = useState('date'); const [ascending, setAscending] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = () => { setError(''); setLoading(true); facilitiesApi.getAdminReservations().then(setRows).catch((e) => setError(apiErrorMessage(e))).finally(() => setLoading(false)) }; useEffect(load, [])
  const filtered = useMemo(() => rows.filter((row) => (filter === 'All' || row.status === filter) && `${row.bookingId} ${row.userId} ${row.userEmail} ${row.space.name}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => { const left = sort === 'id' ? a.bookingId : sort === 'applicant' ? a.userEmail : sort === 'status' ? a.status : a.startDateTime; const right = sort === 'id' ? b.bookingId : sort === 'applicant' ? b.userEmail : sort === 'status' ? b.status : b.startDateTime; const result = typeof left === 'number' && typeof right === 'number' ? left - right : String(left).localeCompare(String(right)); return ascending ? result : -result }), [filter, query, rows, sort, ascending])
  return <Box sx={{ display: 'grid', gap: 3 }}><Typography component="h1" variant="h4" fontWeight={700}>Reservations</Typography><FacilitiesNav />{error ? <ErrorState message={error} retry={load} /> : loading ? <Loading /> : rows.length === 0 ? <Alert severity="info">No reservations found across all accounts.</Alert> : <Card variant="outlined"><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} sx={{ mb: 2 }}><TextField label="Search reservations" value={query} onChange={(e) => setQuery(e.target.value)} size="small" fullWidth /><Select value={filter} onChange={(e) => setFilter(e.target.value)} size="small" aria-label="Filter by reservation status"><MenuItem value="All">All statuses</MenuItem><MenuItem value="CONFIRMED">Confirmed</MenuItem><MenuItem value="COMPLETED">Completed</MenuItem><MenuItem value="CANCELLED">Cancelled</MenuItem></Select><Select value={sort} onChange={(e) => setSort(e.target.value)} size="small" aria-label="Sort reservations"><MenuItem value="date">Sort: Date</MenuItem><MenuItem value="id">Sort: ID</MenuItem><MenuItem value="applicant">Sort: Applicant</MenuItem><MenuItem value="status">Sort: Status</MenuItem></Select><Button size="small" onClick={() => setAscending((value) => !value)}>{ascending ? 'Ascending' : 'Descending'}</Button></Stack><Box sx={{ overflowX: 'auto' }}><Box component="table" sx={tableSx}><thead><tr>{['Reservation ID', 'Facility', 'Applicant', 'Reservation Date', 'Time Slot', 'Status'].map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map((row) => <tr key={row.bookingId}><td>{row.bookingId}</td><td>{row.space.name}</td><td>{row.userEmail} (ID: {row.userId})</td><td>{new Date(row.startDateTime).toLocaleDateString()}</td><td>{new Date(row.startDateTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}–{new Date(row.endDateTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</td><td><Chip label={statusLabel(row.status)} size="small" color={statusColor(row.status)} /></td></tr>)}</tbody></Box></Box></CardContent></Card>}</Box>
}

export function ReservationDetailPage() {
  const { id } = useParams(); const [booking, setBooking] = useState<AdminBooking | null>(null); const [error, setError] = useState('')
  useEffect(() => { if (id) facilitiesApi.getAdminReservationDetail(Number(id)).then(setBooking).catch((e) => setError(apiErrorMessage(e))) }, [id])
  if (error) return <ErrorState message={error} retry={() => window.location.reload()} />; if (!booking) return <Loading />
  return <Box sx={{ display: 'grid', gap: 3, maxWidth: '47.5rem' }}><Typography component="h1" variant="h4" fontWeight={700}>Reservation Detail</Typography><FacilitiesNav /><Card variant="outlined"><CardContent><Stack spacing={2}><Typography variant="h6">Reservation #{booking.bookingId}</Typography><Divider /><Typography><strong>Applicant:</strong> {booking.userEmail} (ID: {booking.userId})</Typography><Typography><strong>Facility:</strong> {booking.space.name}</Typography><Typography><strong>Location:</strong> {booking.space.building} {booking.space.roomNumber}</Typography><Typography><strong>Time:</strong> {reservationLabel(booking.startDateTime, booking.endDateTime)}</Typography><Typography><strong>Status:</strong> {statusLabel(booking.status)}</Typography><Button component={RouterLink} to="/admin/facilities/reservations">Back to Reservations</Button></Stack></CardContent></Card></Box>
}

export function FacilityReservationsPage() {
  const { spaceId } = useParams(); const [rows, setRows] = useState<AdminBooking[]>([]); const [facility, setFacility] = useState<{ name: string; building: string; roomNumber: string } | null>(null); const [error, setError] = useState('')
  useEffect(() => { if (!spaceId) return; Promise.all([facilitiesApi.getAdminReservations(), facilitiesApi.getSpace(Number(spaceId))]).then(([bookings, space]) => { setRows(bookings.filter((booking) => booking.space.spaceId === Number(spaceId)).sort((a, b) => a.startDateTime.localeCompare(b.startDateTime))); setFacility(space) }).catch((e) => setError(apiErrorMessage(e))) }, [spaceId])
  if (error) return <ErrorState message={error} retry={() => window.location.reload()} />; if (!facility) return <Loading />
  return <Box sx={{ display: 'grid', gap: 3 }}><Typography component="h1" variant="h4" fontWeight={700}>Facility Reservation Calendar</Typography><FacilitiesNav /><Card variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 2 }}><Box><Typography variant="h6">{facility.name}</Typography><Typography color="text.secondary">{facility.building} {facility.roomNumber}</Typography></Box><Button component={RouterLink} to="/admin/facilities">Back to Dashboard</Button></Stack><Box sx={{ overflowX: 'auto' }}><Box component="table" sx={tableSx}><thead><tr>{['Date', 'Time', 'Applicant', 'Status', 'Details'].map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={5}>No reservations found for this facility.</td></tr> : rows.map((row) => <tr key={row.bookingId}><td>{new Date(row.startDateTime).toLocaleDateString()}</td><td>{new Date(row.startDateTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}–{new Date(row.endDateTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</td><td>{row.userEmail} (ID: {row.userId})</td><td><Chip label={statusLabel(row.status)} size="small" color={statusColor(row.status)} /></td><td><Button component={RouterLink} to={`/admin/facilities/reservations/${row.bookingId}`} size="small">Detail</Button></td></tr>)}</tbody></Box></Box></CardContent></Card></Box>
}

export function MaintenancePage() {
  const [rows, setRows] = useState<MaintenanceRequest[]>([]); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All'); const [priority, setPriority] = useState('All'); const [sort, setSort] = useState('date'); const [ascending, setAscending] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = () => { setError(''); setLoading(true); facilitiesApi.getAdminMaintenance().then(setRows).catch((e) => setError(apiErrorMessage(e))).finally(() => setLoading(false)) }; useEffect(load, [])
  const filtered = useMemo(() => rows.filter((row) => (filter === 'All' || row.status === filter) && (priority === 'All' || row.priority === priority) && `${row.ticketId} ${row.spaceName ?? ''} ${row.description}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => { const left = sort === 'id' ? a.ticketId : sort === 'facility' ? (a.spaceName ?? '') : sort === 'priority' ? a.priority : sort === 'status' ? a.status : a.createdAt; const right = sort === 'id' ? b.ticketId : sort === 'facility' ? (b.spaceName ?? '') : sort === 'priority' ? b.priority : sort === 'status' ? b.status : b.createdAt; const result = typeof left === 'number' && typeof right === 'number' ? left - right : String(left).localeCompare(String(right)); return ascending ? result : -result }), [filter, priority, query, rows, sort, ascending])
  return <Box sx={{ display: 'grid', gap: 3 }}><Typography component="h1" variant="h4" fontWeight={700}>Maintenance Requests</Typography><FacilitiesNav />{error ? <ErrorState message={error} retry={load} /> : loading ? <Loading /> : rows.length === 0 ? <Alert severity="info">No maintenance requests found across all accounts.</Alert> : <Card variant="outlined"><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} sx={{ mb: 2 }}><TextField label="Search maintenance" value={query} onChange={(e) => setQuery(e.target.value)} size="small" fullWidth /><Select value={filter} onChange={(e) => setFilter(e.target.value)} size="small" aria-label="Filter by maintenance status"><MenuItem value="All">All statuses</MenuItem><MenuItem value="SUBMITTED">Submitted</MenuItem><MenuItem value="IN_PROGRESS">In progress</MenuItem><MenuItem value="RESOLVED">Resolved</MenuItem><MenuItem value="CANCELLED">Cancelled</MenuItem></Select><Select value={priority} onChange={(e) => setPriority(e.target.value)} size="small" aria-label="Filter by maintenance priority"><MenuItem value="All">All priorities</MenuItem><MenuItem value="HIGH">High</MenuItem><MenuItem value="MEDIUM">Medium</MenuItem><MenuItem value="LOW">Low</MenuItem></Select><Select value={sort} onChange={(e) => setSort(e.target.value)} size="small" aria-label="Sort maintenance"><MenuItem value="date">Sort: Date</MenuItem><MenuItem value="id">Sort: ID</MenuItem><MenuItem value="facility">Sort: Facility</MenuItem><MenuItem value="priority">Sort: Priority</MenuItem><MenuItem value="status">Sort: Status</MenuItem></Select><Button size="small" onClick={() => setAscending((value) => !value)}>{ascending ? 'Ascending' : 'Descending'}</Button></Stack><Box sx={{ overflowX: 'auto' }}><Box component="table" sx={tableSx}><thead><tr>{['Request ID', 'Facility', 'Issue', 'Priority', 'Status', 'Submitted Date', ''].map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map((row) => <tr key={row.ticketId}><td>{row.ticketId}</td><td>{row.spaceName ?? `${row.building} ${row.roomNumber}`}</td><td>{row.description}</td><td><Chip label={row.priority} size="small" color={row.priority === 'HIGH' ? 'error' : 'default'} /></td><td><Chip label={statusLabel(row.status)} size="small" color={statusColor(row.status)} /></td><td>{new Date(row.createdAt).toLocaleDateString()}</td><td><Button component={RouterLink} to={`/admin/facilities/maintenance/${row.ticketId}`} size="small">View</Button></td></tr>)}</tbody></Box></Box></CardContent></Card>}</Box>
}

export function MaintenanceDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [request, setRequest] = useState<MaintenanceRequest | null>(null); const [status, setStatus] = useState('SUBMITTED'); const [error, setError] = useState('')
  useEffect(() => { if (id) facilitiesApi.getAdminMaintenanceDetail(Number(id)).then((data) => { setRequest(data); setStatus(data.status) }).catch((e) => setError(apiErrorMessage(e))) }, [id])
  const save = () => { if (!id) return; facilitiesApi.updateMaintenance(Number(id), status).then(() => navigate('/admin/facilities/maintenance')).catch((e) => setError(apiErrorMessage(e))) }
  if (error) return <ErrorState message={error} retry={() => window.location.reload()} />; if (!request) return <Loading />
  return <Box sx={{ display: 'grid', gap: 3, maxWidth: '47.5rem' }}><Typography component="h1" variant="h4" fontWeight={700}>Maintenance Detail</Typography><Card variant="outlined"><CardContent><Stack spacing={2}><Typography variant="h6">#{request.ticketId} · {request.spaceName ?? `${request.building} ${request.roomNumber}`}</Typography><Divider /><Typography><strong>Problem:</strong> {request.description}</Typography><Typography><strong>Request time:</strong> {new Date(request.createdAt).toLocaleString()}</Typography><Typography><strong>Current status:</strong> {statusLabel(request.status)}</Typography><Select value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Maintenance status">{nextStatuses(request.status).map((value) => <MenuItem key={value} value={value}>{statusLabel(value)}</MenuItem>)}</Select><Stack direction="row" spacing={2}><Button variant="contained" onClick={save} disabled={status === request.status}>Save Changes</Button><Button component={RouterLink} to="/admin/facilities/maintenance">Cancel</Button></Stack></Stack></CardContent></Card></Box>
}
